# Generated by Django 5.2.7 on 2025-10-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('estimated_gdp', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
