# Generated by Django 5.2.7 on 2025-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='countries_name_19480f_idx'),
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
    ]
